### PR TITLE
Update for new deps versions, updated Rust

### PR DESCRIPTION
**Pull request by jamesmunns**
Note: Shouldn't land until https://github.com/braun-robotics/rust-dw1000/pull/62 has, and the SHA has been updated (or removed) in this Cargo.toml

### CODE REVIEW

**Comment by hannobraun** [comment]
Looks good to me, aside from the caveats you mentioned. Thank you, @jamesmunns!

**Comment by hannobraun** [comment]
https://github.com/braun-robotics/rust-dw1000/pull/62 has been merged, which means this is unblocked.

**Comment by jamesmunns** [comment]
@hannobraun I think this is ready to merge now. It would probably be good to release an initial version of the `dw1000` and `dwm1001` crates.

For now, this repo will track `master` of `dw1000`.

**Comment by hannobraun** [comment]
Thank you, @jamesmunns!

> I think this is ready to merge now. It would probably be good to release an initial version of the `dw1000` and `dwm1001` crates.
> 
> For now, this repo will track `master` of `dw1000`.

You're totally right. I've [started working](https://github.com/braun-robotics/ieee-802.15.4/compare/master...hannobraun:cleanup) on releasing `ieee802154` (as that's a prerequisite for the other two), but I've hit some unexpected hurdles these past two months (unrelated to these crates), which inhibited my progress. I expect to be back on track in January.

**Pull request merged**
