### PR TITLE
WIP: RTFM templates

### PR DESCRIPTION
**Pull request by jamesmunns**
Do not merge until #59 lands

### CODE REVIEW

**Comment by hannobraun** [comment]
#59 has landed. This could use a rebase.

**Comment by jamesmunns** [comment]
@hannobraun rebased, I'll keep working on this today, and get it at a clean stopping point, then rebase a bit. I'm a bit unsure if this is merge ready, I think it is a useful example, though I have found some issues (https://github.com/japaric/cortex-m-rtfm/issues/123, https://github.com/japaric/cortex-m-rtfm/issues/121) in how I use rtfm, so I might need to use less unstable features for these templates.

**Comment by hannobraun** [comment]
Needs a rebase.

@jamesmunns I'm starting to prepare for the initial crates.io release now. I'm not sure when that will happen, as I haven't decided which issues to close first, but if you want this pull request to be included, it needs to be merged soon-ish.

**Comment by hannobraun** [comment]
Hey James, are you still intending to do something with this PR? I'm asking because the branch still exists, and I don't want to have too many unused branches in the main repository, to prevent user confusion.

**Comment by hannobraun** [comment]
@jamesmunns ping

**Pull request closed without merging**
